Добавлена валидация при приеме запросов
IlyaKo/pet-holidays pull request #38
Opened 2024-10-21 09:49 UTC by Desann69

2024-10-21 11:16 UTC, IlyaKo commented on .DS_Store
Надо добавить в gitignore это расширение `.DS_Store` - это Мак ОС создаёт файлики, в репозитории они не нужны

2024-10-21 11:16 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.WebApi/Extensions/ServiceCollectionExtensions.cs
> +        string? connectionString = configuration.GetConnectionString("CoreDb");
Здесь и дальше по коду почему-то изменен только `var` на конкретный тип. 
Я бы предложил в рамках этого PR не менять ну и вообще договориться использовать `var` где это возможно - так как это очень удобно не отвлекать внимание на конкретный тип. Если что - IDE умеют подсказывать что это за тип очень хорошо, а во многих случаях вообще не обязательно знать что это за тип.

2024-10-21 11:16 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.WebApi/Extensions/ServiceCollectionExtensions.cs
> +        //services.AddValidatorsFromAssembly(Assembly.GetExecutingAssembly());
Лучше не допускать закомментированного кода в основные ветки проекта - т.е. где-то для тестирования, в отдельной ветке - это может быть удобно, но в целом лучше убирать из кода.

2024-10-21 11:16 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.WebApi/Extensions/ServiceCollectionExtensions.cs
> +        services.AddSingleton<IValidator<HotelEditDto>,  HotelEditDtoValidator>();
Предлагаю здесь находить все валидаторы автоматически, так как ты выше закомментировал - `services.AddValidatorsFromAssembly`

2024-10-21 11:16 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.WebApi/Validations/HotelEditDtoValidator.cs
> +public class HotelEditDtoValidator : AbstractValidator<HotelEditDto>
Предлагаю весь код перенести в проект Application, там есть уже папка Hotels для этих штук

2024-10-21 11:16 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.WebApi/Endpoints/HotelEndpoints.cs
> +            //IValidator<HotelEditDto> validateService = app.Services.GetService<IValidator<HotelEditDto>>();
Весь код по валидации лучше перенести в сервисный класс `HotelService` - чтобы этот класс отвечал именно за эндпоинты и их маппинг

2024-10-21 11:16 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.WebApi/Endpoints/HotelEndpoints.cs
> +            FluentValidation.Results.ValidationResult validationResult = validateService.Validate(dto);
Есть метод `ValidateAndThrow` или как-то так - чтобы не писать каждый раз однотипный код

2024-10-21 11:18 UTC, Desann69 commented on .DS_Store
Принято! Добавлю со следующим PR

2024-10-21 11:27 UTC, IlyaKo commented on .DS_Store
На то комментарии и есть, чтобы в рамках этого PR исправления вносить - так легче будет отслеживать комментарии

2024-10-21 12:56 UTC, Desann69 commented on src/backend/LosTomates.PetHolidays.WebApi/Extensions/ServiceCollectionExtensions.cs
> +        string? connectionString = configuration.GetConnectionString("CoreDb");
Насчет коррекций в PR согласен, но лучше использовать, мне кажется, явные типы, чтобы быстрее улавливать контекст

2024-10-28 17:59 UTC, pavel1387 approved these changes

2024-10-28 18:02 UTC, pavel1387 approved these changes

2024-10-28 19:21 UTC, IlyaKo commented on .DS_Store
Что-то файлики не исчезли, может надо еще руками их удалить? Попробуй прямо в браузере эти файлики удалить:
![image](https://github.com/user-attachments/assets/473e9998-f558-4824-aa4b-4eac5c770f7b)

2024-10-28 19:28 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.WebApi/Extensions/ServiceCollectionExtensions.cs
> +        string? connectionString = configuration.GetConnectionString("CoreDb");
Если согласен насчет того, чтобы не менять в PR - тогда надо бы вернуть `var` на место 😃

2024-10-28 20:02 UTC, IlyaKo commented
Можно подтянуть еще изменения из ветки Develop и добавить Middleware обработчик для исключений валидации, так как сейчас возвращается ошибка 500

2024-10-28 20:04 UTC, IlyaKo requested changes

2024-10-28 20:04 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Validations/HotelEditDtoValidator.cs
Можно упростить до такого:
```
public HotelEditDtoValidator()
{
    RuleFor(customer => customer.Name).MaximumLength(DatabaseConstrains.NameMaxLength);
    RuleFor(customer => customer.Description).MaximumLength(DatabaseConstrains.DescriptionMaxLength);
}
```
Будет такой же результат, сообщение будет автоматически генерироваться. 
`MaximumLength` игнорирует null, а пустой результат всегда меньше

2024-10-28 20:05 UTC, IlyaKo commented
@Desann69 Можно опубликовать обратно PR, а то он всё еще в draft'e

2024-10-30 11:45 UTC, Koltrop approved these changes

2024-11-06 18:49 UTC, IlyaKo requested changes

2024-11-06 18:49 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Validations/HotelEditDtoValidator.cs
> +                                                 .When(v => !string.IsNullOrEmpty(v.Description));
Здесь условие в When не нужно, без него точно так же работает

2024-11-06 18:49 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Validations/HotelEditDtoValidator.cs
> +    public override ValidationResult Validate(ValidationContext<HotelEditDto> context)
Оверрайдить метод тоже не нужно - стандартная реализация хорошо описывает ошибки

2024-11-06 18:49 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.WebApi/Endpoints/HotelEndpoints.cs
> +            HotelView? entityView = await service.GetById(hotelId);
Тут `var` вернуть как было

2024-11-06 18:49 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.WebApi/Program.cs
> +        SeedService seedService = scope.ServiceProvider.GetRequiredService<SeedService>();
Тут тоже `var` вернуть как было

2024-11-06 18:49 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Hotels/HotelService.cs
> +        bool isValid = entityId >= 0;
А нужно ли это валидировать? Это исключительная ситуация, когда сюда что-то не то прислали - но если не будет этих строчек, то приложение итак вернёт ошибку `NotFoundException`

2024-11-06 18:49 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Hotels/HotelService.cs
> +        bool isValid = entityId >= 0;
Это private метод, тут не должно быть такого исключения

2024-11-06 18:49 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Exceptions/ValidationBadRequest.cs
Я бы вообще удалил этот класс, если нужно бросить исключение валидации - тогда я бы использовал то, которое уже есть - `FluentValidation.ValidationException`

2024-11-07 11:01 UTC, Desann69 reviewed
When убрал
Но с DS_Store убрать из первого коммита не удалось

2024-11-07 15:54 UTC, IlyaKo commented on .DS_Store
Удалил в итоге файлики сам

2024-11-07 15:57 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Hotels/HotelService.cs
> +        bool isValid = entityId >= 0;
В delete тоже надо убрать эту валидацию

2024-11-07 19:23 UTC, IlyaKo approved these changes

2024-11-07 19:23 UTC, merged