add mapster
IlyaKo/pet-holidays pull request #44
Opened 2024-10-30 10:05 UTC by pavel1387

2024-10-30 19:38 UTC, IlyaKo requested changes

2024-10-30 19:38 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Mapping/HotelMappingConfig.cs
> +namespace LosTomates.PetHolidays.Application.Mapping
Предлагаю перенести это в папку Hotels и в соответствующий namespace: `LosTomates.PetHolidays.Application.Hotels`, соответственно сам класс тогда можно назвать просто `MappingConfig`

2024-10-30 19:38 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Mapping/HotelMappingConfig.cs
> +namespace LosTomates.PetHolidays.Application.Mapping
Здесь и в остальных местах предлагаю использовать file-scoped namespace - чтобы меньше вложенность была

2024-10-30 19:38 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Mapping/HotelMappingConfig.cs
> +using System.Threading.Tasks;
Можно удалить лишние using - можно по кнопочке `Run Code Cleanup` если ты в VS

2024-10-30 19:38 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Mapping/ServiceCollectionExtension.cs
> +namespace LosTomates.PetHolidays.Application.Mapping
Предлагаю папку и namespace переименовать в Extensions

2024-10-30 19:38 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Hotels/HotelService.cs
> +        return _mapper.Map<HotelView>(entity);
Можно маппить через метод расширения Adapt: 
```
return entity.Adapt<HotelView>();
```
Тогда регистрация сервиса IMapper не нужна, так и собственно зависимость в этом классе

2024-10-30 19:38 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Hotels/HotelService.cs
> +                 ?? throw new NotFoundException("hotel", entityId.ToString());
Здесь не обязательно, но можно использовать `nameof(Hotel)` чтобы избавиться от "магических строк" в коде, которые сложно поддерживать

2024-10-30 19:38 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Hotels/HotelService.cs
> +        => _mapper.Map<List<HotelView>>(await dbContext.Hotels.Where(x => x.IsActive).ToListAsync());
Слишком много вложенности получилось, предлагаю переделать на несколько строчек отдельных. 
Либо как вариант использовать проекцию - классная штука мапстера - он делает выборку нужных полей, т.е. метод будет вот так выглядеть:
```
=> await dbContext.Hotels
                  .Where(x => x.IsActive)
                  .ProjectToType<HotelView>()
                  .ToListAsync();
```

2024-10-30 19:38 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Hotels/HotelService.cs
>      {
Для создания и обновления тоже желательно маппинг добавить, т.е. из `HotelEditDto` в `Hotel`

2024-10-31 16:47 UTC, IlyaKo requested changes

2024-10-31 16:47 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Hotels/MappingConfig.cs
> +        config.NewConfig<HotelView, Hotel>();
Здесь вместо `HotelView` нужен `HotelEditDto`, чтобы получилось:
```
config.NewConfig<HotelEditDto, Hotel>();
```

2024-10-31 17:30 UTC, pavel1387 commented on src/backend/LosTomates.PetHolidays.Application/Hotels/MappingConfig.cs
> +        config.NewConfig<HotelView, Hotel>();
@IlyaKo точно, спасибо) без этой настройки не было ошибки в методе HotelService.Create, я думал тут как в AutoMapper, но оказывается можно не создавать файл конфигурации, если свойства у объектов одинаковые по названию

2024-10-31 17:37 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Hotels/MappingConfig.cs
> +        config.NewConfig<HotelView, Hotel>();
Я не знал, что так работает, круто!
Я думаю это можно настроить при регистрации в DI через config мапстера

2024-10-31 17:40 UTC, IlyaKo approved these changes
Огонь! 🔥

2024-11-05 20:27 UTC, Koltrop approved these changes

2024-11-05 21:56 UTC, merged