Tasks/29-add-frontend-to-docker
IlyaKo/pet-holidays pull request #45
Opened 2024-11-04 20:52 UTC by pavel1387

2024-11-05 12:17 UTC, IlyaKo commented on src/frontend/Dockerfile
В итоге работает сервер? Я думал, что для nginx нужно еще config файл скопировать с настройками

2024-11-05 17:36 UTC, pavel1387 commented on src/frontend/Dockerfile
Да, работает без копирования

2024-11-05 19:10 UTC, IlyaKo requested changes

2024-11-05 19:10 UTC, IlyaKo commented on src/frontend/Dockerfile
И правда, у меня тоже сработало. Неужели они переделали это наконец-то, чтобы нормально работало по умолчанию! Может я просто другой образ качал просто раньше

2024-11-05 19:10 UTC, IlyaKo commented on src/frontend/Dockerfile
Предлагаю рядом положить `.dockerignore` файл с таким содержимым:
```
node_modules
.git
.dockerignore
Dockerfile
README.md
*.log
```
Чтобы не копировать эти вещи, так как они не используются всё равно

2024-11-05 19:10 UTC, IlyaKo commented on src/docker-compose.yml
Предлагаю отделить переносами строки сервисы между собой и сети, чтобы проще было читать файл

2024-11-05 19:10 UTC, IlyaKo commented on src/docker-compose.yml
Предлагаю заодно в этом PR поправить мэппинг портов для сервиса БД postgres:
    ```
    ports:
      - "5432:5433"
      ```
Тогда и в контейнерах будет работать и не будет использовать порт, если установлен postgres локально

2024-11-05 19:10 UTC, IlyaKo commented on src/frontend/src/components/layout/Layout.js
Интересно, что git на Windows "не видит" этого изменения и не переименовывает файл - пока я вручную не переименовал

2024-11-05 21:54 UTC, pavel1387 commented on src/docker-compose.yml
получается в данном случаем postgres должен быть либо локально, либо в контейнере? если есть локальный postgres на 5432, то контейнер не запустится же на 5432, верно?

2024-11-05 21:59 UTC, IlyaKo commented on src/docker-compose.yml
Запустится и так и так, потому что `5432:5433` означает мапить 5432 порт контейнера на 5433 порт хоста.
В итоге внутри контейнера и сети pet-holidays-network postgres будет на порту 5432, а "снаружи" как 5433.

2024-11-06 07:03 UTC, pavel1387 commented on src/docker-compose.yml
@IlyaKo наоборот же вроде)

`ports: - "5432:5433"`
то 5432 это локальный порт хоста, а 5433 порт контейнера
https://docs.docker.com/compose/how-tos/networking/

или я неправильно понял)

2024-11-06 10:08 UTC, IlyaKo commented on src/docker-compose.yml
Это я всё наоборот понял) Ты правильно всё сделал, извиняюсь, попутал 😣

2024-11-06 10:12 UTC, IlyaKo approved these changes
Мне нравится! Единственное, я бы делал контекст докерфайлов, чтобы он соответствовал папкам где они лежат, а сейчас сделано так, что они работают только на уровень выше. Но это не проблема, я бы оставил как есть 👍

2024-11-06 11:30 UTC, merged