add User and identity core
IlyaKo/pet-holidays pull request #49
Opened 2024-11-08 20:04 UTC by Koltrop

2024-11-11 19:30 UTC, IlyaKo requested changes

2024-11-11 19:30 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.DataAccess/Migrations/20241108182435_user1.cs
Похоже лишняя миграция пустая - надо удалить

2024-11-11 19:30 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.DataAccess/ApplicationDbContext.cs
> +public sealed class ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : IdentityDbContext(options)
Можно использовать обобщенный тип здесь `IdentityDbContext<T>` - чтобы наш класс пользователя туда передать:
```
public sealed class ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) 
    : IdentityDbContext<User>(options)
```
Тогда можно будет удалить поле Users из класса и не скрывать его как сейчас происходит.
Из-за сокрытия поля - EF создаёт колонку Discriminator, чтобы хранить разные типы (User и IdentityUser) в одной таблице. Поэтому придётся перегенировать миграцию, после этого исправления

2024-11-11 19:30 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.DataAccess/ApplicationDbContext.cs
> +        modelBuilder.Entity<User>();
Здесь можно не добавлять пустую настройку, Entity Framework увидит поле Users в унаследованном классе и будет учитывать в модели данных

2024-11-11 19:30 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Core/LosTomates.PetHolidays.Core.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.10" />
UI Nuget пакет не нужен, предлагаю удалить

2024-11-11 19:30 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.DataAccess/Migrations/20241108170240_user.cs
> +    public partial class user : Migration
Миграцию лучше называть по тем же правилам, что и класс в C# - т.е. PascalCase - с большой буквы. Тогда при генерации класса не будет предупреждения показывать о нарушении правил именования. И чтобы не мешал в использовании - надо подлиннее имя давать - например, AddUserTables

2024-11-11 19:30 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Users/UserService.cs
> +    private readonly UserManager<IdentityUser> _userManager;
Здесь можно передать наш тип пользователя - User вместо IdentityUser

2024-11-11 19:30 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.WebApi/LosTomates.PetHolidays.WebApi.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.10" />
Здесь тоже не нужен Nuget пакет UI

2024-11-11 19:30 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.WebApi/Program.cs
> +        app.UseHttpsRedirection();
Мы планируем прятать наш бэк за Gateway'ем, поэтому на не нужно
`app.UseHttpsRedirection();`

2024-11-11 19:30 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.WebApi/Program.cs
> +        app.UseStaticFiles();
У нас фронт будет в отдельном сервере на Nginx работать и файлы мы вроде не храним никакие статично - для них у нас отдельный сервис будет, соответственно я бы убрал `app.UseStaticFiles();`

2024-11-11 19:30 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.WebApi/Program.cs
> +        services.AddDefaultIdentity<IdentityUser>(options => options.SignIn.RequireConfirmedAccount = true)
Так как ты свои Enpoint'ы добавил (и правильно сделал, я считаю) - то это здесь не нужно, так как относится к Identity.UI. 
Вместо этого надо использовать один из методов - `AddIdentityCore<User>` если мы хотим без ролей своих, но если хотим использовать роли - тогда метод `AddIdentity<User, IdentityRole>()`.
А вызов `AddEntityFrameworkStores<ApplicationDbContext>()` оставить, т.е. получится вот так:
```
  services.AddIdentity<User, IdentityRole>()
          .AddEntityFrameworkStores<ApplicationDbContext>();
```

2024-11-11 19:30 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.WebApi/Program.cs
> +        app.UseAuthentication();
Надо удалить пока что, чтобы использовать схему - надо задать какую-то по умолчанию, а это в следующей задаче надо будет сделать - где как раз генерить токены. Если оставить и поменять выше так, как я предлагаю - то будет ошибку показывать.

2024-11-11 19:30 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Validations/UserEditDtoValidator.cs
> +    public UserEditDtoValidator() { }
Я предлагаю добавить `RuleFor(x => x.Email).EmailAddress()` и посмотреть какие ограничения для устанавливаемых полей в БД есть (в миграции, как например посмотреть) - и здесь их проверять. Чтобы отловить здесь ошибки и показать понятный текст, а не исключение при записи в БД

2024-11-12 20:37 UTC, IlyaKo requested changes
Класс, мне нравится как получилось! Особенно меня порадовало, что ты удалил все миграции лишние и сделал одну новую 💪💪💪
Маленькое замечание по методу создания пользователя - немного выбивается от подхода в остальных методах.

2024-11-12 20:37 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Users/UserService.cs
> +    public async Task<string> Create(UserEditDto dto)
Мне кажется неправильно возвращать ошибки иногда вместо Id созданного пользователя. 
Предлагаю сделать также как и в остальных случаях: бросать исключение, если не прошло валидацию - т.е. использовать `validateService.ValidateAndThrow(dto);` для проверки dto, а если _userManager вернёт ошибки, тогда тоже бросать `ValidationException`. У нас будет middleware, который это исключение обработает

2024-11-12 20:37 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Users/UserService.cs
> +            var user = new User { UserName = dto.UserName, Email = dto.Email, PhoneNumber = dto.PhoneNumber };
Здесь можно mapster использовать тоже:
```
var user = dto.Adapt<User>();
```

2024-11-12 20:37 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.WebApi/Endpoints/UserEndpoints.cs
> +            if (Guid.TryParse(result, out _))
Здесь соответственно логика упростится, если возвращать только Id пользователя, иначе бросать исключение внутри метода

2024-11-14 16:04 UTC, IlyaKo approved these changes

2024-11-18 12:50 UTC, Desann69 approved these changes

2024-11-18 15:28 UTC, pavel1387 approved these changes
Мне все нравится 👍

2024-11-18 15:32 UTC, merged