#42 add rooms and room types
IlyaKo/pet-holidays pull request #51
Opened 2024-11-16 16:14 UTC by IlyaKo

Добавил сущность номеров и их типов.
Привязал их к отелю, как у нас в БД было описано - зацените, нормально ли получилось.
Пользователей и животных не добавлял еще для номеров, так как их пока еще нет в ветке develop.

2024-11-25 12:11 UTC, pavel1387 requested changes

2024-11-25 12:11 UTC, pavel1387 commented on src/backend/LosTomates.PetHolidays.Core/Domain/Rooms/RoomType.cs
> +    public int HotelId { get; set; }
Решили на созвоне, что типы комнат будут одинаковые для всех отелей и решили убрать HotelId для RoomType.

2024-11-26 21:09 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Core/Domain/Rooms/RoomType.cs
> +    public int HotelId { get; set; }
Убрал

2024-11-26 21:12 UTC, IlyaKo commented
Возможно придётся почистить базу, чтобы миграция применилась заново

2024-11-29 13:30 UTC, pavel1387 approved these changes

2024-11-29 16:38 UTC, Koltrop approved these changes

2024-11-30 09:03 UTC, Desann69 approved these changes

2024-11-30 18:41 UTC, merged