add generation jwt token
IlyaKo/pet-holidays pull request #63
Opened 2024-12-09 22:49 UTC by Koltrop

2024-12-10 08:58 UTC, Desann69 approved these changes

2024-12-10 20:09 UTC, IlyaKo requested changes

2024-12-10 20:09 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Users/UserService.cs
> +        this._secretKey = configuration["JwtSettings:SecretKey"];
Предлагаю тут добавить проверку что он заполнен. Тогда не будет еще предупреждений от IDE что здесь может быть null. Например, вот так:
```
var configuredKey = configuration["JwtSettings:SecretKey"];        
if(string.IsNullOrEmpty(configuredKey))
    throw new ApplicationException("You need to set up the JWT secret key");
this._secretKey = configuredKey;
```

2024-12-10 20:09 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Users/UserService.cs
> +            throw new NotFoundException(nameof(User), dto.Email);
Тут по идее тоже надо бросать Invalid credentials - чтобы злоумышленник не мог перебом понять какие e-mail есть уже в системе. Можно вот так, кстати, записать:
```
var user = await _userManager.FindByEmailAsync(dto.Email)
    ?? throw new UnauthorizedAccessException("Invalid credentials");
```

2024-12-10 20:09 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Users/UserService.cs
> +    public async Task<(string UserId, string UserName)>  GetUserFromToken(string token)
Метод синхронный, поэтому можно убрать async Task
```suggestion
    public (string UserId, string UserName) GetUserFromToken(string token)
```
Соответственно придется поправить и в интерфейсе и там где вызывается этот метод в `UserEnpoints`

2024-12-10 20:09 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Users/UserService.cs
> +        var result = await _signInManager.CheckPasswordSignInAsync(user, dto.Password, false);
Этот метод есть в `_userManager.CheckPasswordAsync`, предлагаю использовать его и тогда можно будет удалить SignInManager

2024-12-10 20:09 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.WebApi/Endpoints/UserEndpoints.cs
> +        mapGroup.MapPost("GetUserFromToken", async (IUserService service, string dto) =>
Смысл JWT токена, что фронтенду не надо делать запрос на бэк после логина, чтобы понять что там за пользователь - он также расшифрует этот токен, только поменять его не сможет - так как не знает секретного ключа.
Я имел ввиду не endpoint, а метод IUserService - например, с именем GetCurrentUserId() - который будет возвращать пользователя, от имени которого делается запрос. Этим методом мы будем пользоваться только в рамках бэкенда. 
Если хочется добавить endpoint, то он может быть такой:
GET CurrentUser, без параметров - который по токену определит UserId, вытащит из базы по нему пользователя, смапит на модель UserView и вернёт её.

2024-12-11 17:32 UTC, Koltrop commented on src/backend/LosTomates.PetHolidays.WebApi/Endpoints/UserEndpoints.cs
> +        mapGroup.MapPost("GetUserFromToken", async (IUserService service, string dto) =>
думаю что для этого надо добавить httpcontextaccessor 
делаем это на эту задачу?

2024-12-11 20:17 UTC, IlyaKo approved these changes

2024-12-11 20:17 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.WebApi/Extensions/ServiceCollectionExtensions.cs
> +            //for test tokens
Этот код надо расскоментировать, пусть он будет в сваггере.

2024-12-12 15:54 UTC, merged