Tasks/28 docker
IlyaKo/pet-holidays pull request #64
Opened 2024-12-10 12:55 UTC by pavel1387

Переименовать в compose.yml не получилось, видимо студия ожидает docker-compose.yml

2024-12-10 21:02 UTC, IlyaKo requested changes

2024-12-10 21:02 UTC, IlyaKo commented on src/docker-compose.yml
> +  pet-holidays-core-volume:
Надо также переименовать в `postgres: volumes`, получится что-то типа:
```
volumes:
  - pet-holidays-core-volume:/var/lib/postgresql/data
```

2024-12-11 13:43 UTC, Desann69 approved these changes

2024-12-15 16:26 UTC, IlyaKo approved these changes
![PoutKissGIF](https://github.com/user-attachments/assets/3ff3a3da-93f5-4b60-b3e6-069275958850)

2024-12-16 17:39 UTC, Desann69 approved these changes

2024-12-17 08:44 UTC, merged