Tasks/16 tests web api
IlyaKo/pet-holidays pull request #65
Opened 2024-12-12 12:04 UTC by Desann69

2024-12-12 18:38 UTC, IlyaKo commented
Сейчас еще и не проходят тесты, если их все разом запустить подряд

2024-12-12 18:42 UTC, IlyaKo commented
@Desann69 а тебе VS Code не показывает предупреждения? Те, которые сейчас видно на закладке Files changes, как например: `Support for 'async void' unit tests is being removed from xUnit.net v3. To simplify upgrading, convert the test to 'async Task' instead.`

2024-12-12 19:50 UTC, IlyaKo requested changes

2024-12-12 19:50 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Tests/RoomServiceTests.cs
> +    private void SeedHotelAndRoom(out int hotelId, out int roomId, out EntityEntry<Hotel> hotelEntity, out EntityEntry<Room> roomEntity)
Странно метод сделан - если возвращается сам созданный объект, у которого есть id - то зачем еще возвращать id объекта? Причем в тестовых методах где-то через EntityEntryобращается, где-то через id. 
Предлагаю вместо этого метода сделать два метода - один для отеля, другой для комнаты. И возвращать тип не через Out параметры, а просто возвращать класс. Причём не EntityEntry, а просто Hotel или Room

2024-12-12 19:50 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Tests/RoomServiceTests.cs
> +        var result = await _roomService.GetAll(hotelId);
Тут возвращается 0 строчек, так как метод GetAll использует mapster под капотом, а он не замокан. На уроке с тестами Роман показывал как можно сервисы приложения все автоматически зарегестрировать, я думаю здесь также надо сделать. [Вот пример](https://github.com/IlyaKo/otus-promocode-factory/blob/3de107e9a13774f6802a2eb6c91015a918b9b63e/UnitTests/src/PromoCodeFactory.UnitTests/TestFixtures/FixtureWithInMemoryDatabase.cs), опять же из домашки

2024-12-15 13:51 UTC, pavel1387 commented
предлагаю тесты перенести в папку src/tests

2024-12-15 18:15 UTC, Desann69 commented on src/backend/LosTomates.PetHolidays.Tests/RoomServiceTests.cs
> +        var result = await _roomService.GetAll(hotelId);
Исправил, сидинг. Добавил Fixture, однако при поиске строки подключения, генерируется ошибка с нашей стороны

2024-12-15 18:18 UTC, Desann69 commented on src/backend/LosTomates.PetHolidays.Tests/RoomServiceTests.cs
> +        var result = await _roomService.GetAll(hotelId);
Как вариант, наверно можно вручную добавлять в конфигурацию строку или чтобы ключ был, а значения нет

2024-12-15 18:44 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Tests/RoomServiceTests.cs
> +        var result = await _roomService.GetAll(hotelId);
Это можно поправить добавив туда значение просто, т.е. в fixture что-то типа такого написать:
```
var configurationBuilder = new ConfigurationBuilder();

var inMemorySettings = new Dictionary<string, string?> 
{
    {"ConnectionStrings:CoreDb", "Empty connection string"},
};
configurationBuilder.AddInMemoryCollection(inMemorySettings);

var configuration = configurationBuilder.Build();

var services = new ServiceCollection();
WebApi.Program.AddServices(services, configuration);
```

2024-12-15 18:51 UTC, IlyaKo commented
Надо версии для 8-го дотнета устанавливать, так как у нас все для него сейчас. Так что поправь версию NuGet'a для провайдера БД в памяти:
`<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.11" />`

2024-12-15 18:58 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Tests/RoomServiceTests.cs
> +        var result = await _roomService.GetAll(hotelId);
Похоже mapster не умеет работать с провайдером этим чтобы сделать правильно проекцию. Видимо надо будет переделать GetAll метод - сначала выгрузить из БД, а потом уже мапстер вызвать:
```
public async Task<IReadOnlyList<RoomView>> GetAll(int hotelId)
{
    var entities = await _dbContext.Rooms
                                   .Where(x => x.HotelId == hotelId)                               
                                   .ToListAsync();

    return entities.Adapt<IReadOnlyList<RoomView>>(); 
}
```

2024-12-16 16:30 UTC, IlyaKo approved these changes
Почему-то тесты именно в CI не проходят, предлагаю опубликовать PR и потом посмотреть почему это происходит?

2024-12-16 16:51 UTC, Desann69 commented
Да, наверно резонно так сделать

2024-12-16 17:21 UTC, merged