Tasks/54 pets crud
IlyaKo/pet-holidays pull request #66
Opened 2024-12-16 09:39 UTC by pavel1387

2024-12-16 17:37 UTC, Desann69 approved these changes

2024-12-17 20:18 UTC, IlyaKo requested changes

2024-12-17 20:18 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Pets/PetEditDto.cs
Так как этот объект нам присылает кто-то, то мы не планируем его менять, поэтому можно сделать как sealed record и полям поставить модификатор доступа init

2024-12-17 20:18 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.DataAccess/ApplicationDbContext.cs
> +                  .HasMaxLength(DatabaseConstrains.NameMaxLength)
Желательно это ограничение продублировать в валидатор, чтобы ошибка была не при записи в БД, а во время валидации - там будет текст понятный, а то сейчас вернется ошибка 500 и придётся разбираться почему это произошло

2024-12-17 20:18 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Pets/MappingConfig.cs
> +             .Map(dest => dest.PetType, src => src.PetType != null ? src.PetType.Name : "Unknown");
Судя по сервисному классу PetType будет всегда заполнен, так как во время создания проверяется id на то, что он существует. Поэтому тут будет Unknown только если мы что-то не так сделали в коде, например, забыли нужный Include при получении данных из базы. Поэтому я бы удалил эту строчку здесь.

2024-12-17 20:18 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Pets/PetView.cs
> +    public string? PetType { get; set; }
Предлагаю PetTypeView для PetType сделать, mapster знает о том, как маппить эти типы - поэтому он заполнится, если будет навигационное поле заполнено.

2024-12-17 20:18 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.DataAccess/ApplicationDbContext.cs
> +                  .HasDefaultValue("Not set");
Предлагаю явно хранить null если не задано имя, а клиент (в нашем случае фронтенд) будет сам решать как ему null выводить - либо это текст будет, либо прятать поле на страничке и т.д.

2024-12-17 20:18 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Validations/PetEditDtoValidator.cs
Не уследил в предыдущих PR, но эти файлы на мой вгляд лучше будут лежать рядом с остальными по какой-то сущности, в данном случае в папке Pets

2024-12-17 20:18 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.WebApi/Endpoints/PetEndpoints.cs
Оффтопик: мы можем здесь пользователя не передавать (параметр userId), если сделать следующее:
- добавить ограничение на эти эндпоинты, что они доступны только авторизованному пользователю с ролью "pet-owner"
- запросы будут тогда проходить только если будет указан JWT токен
- если добавить параметр ClaimsPrincipal - тогда туда будет заинжекчен набор claims пользователя, который делает запрос. Среди них будет userId

В рамках данного PR предлагаю оставить все как есть

2024-12-17 20:18 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.WebApi/Extensions/ServiceCollectionExtensions.cs
> -using FluentValidation;
За это отдельное спасибо!
![SmilingSmilingCatGIF](https://github.com/user-attachments/assets/577d4863-36fd-44f4-8e3e-0a4020d47474)

2024-12-18 07:32 UTC, pavel1387 commented
@IlyaKo <img src="https://media4.giphy.com/media/l0Iyl55kTeh71nTXy/giphy.gif"/>

2024-12-18 08:19 UTC, IlyaKo approved these changes
![FeednanyangiLunaJaeminGIF](https://github.com/user-attachments/assets/be79c5ad-35f4-4ce3-b924-e824ca881a20)

2024-12-18 08:19 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Pets/PetView.cs
> +    public PetTypeView? PetType { get; set; }
Так как у нас всегда будет он заполнен, то можно убрать признак nullable здесь, вот так сделать:
```suggestion
    public required PetTypeView PetType { get; set; }
```

2024-12-18 08:43 UTC, merged