Tasks/41 crud для bookings на webapi
IlyaKo/pet-holidays pull request #81
Opened 2024-12-26 13:51 UTC by Desann69

Добален CRUD для Bookings

2024-12-26 19:20 UTC, pavel1387 commented on src/backend/LosTomates.PetHolidays.DataAccess/DatabaseConstrains.cs
> +    public const int UserIdMaxLength = 50;
Думаю что здесь не нужен UserIdMaxLength, userId это же Guid и у него фиксированная длина

2024-12-26 19:20 UTC, pavel1387 commented on src/backend/LosTomates.PetHolidays.Application/Bookings/IBookingsService.cs
> +}
думаю надо добавить метод получения всех Booking по UserId

2024-12-26 19:20 UTC, pavel1387 commented on src/backend/LosTomates.PetHolidays.Application/Bookings/BookingDto.cs
> +}
ну здесь все поля наверное надо сделать required

2024-12-26 19:20 UTC, pavel1387 commented on src/backend/LosTomates.PetHolidays.Application/Bookings/BookingView.cs
> +}
Тут еще нужно добавить PetView и RoomView

2024-12-26 19:20 UTC, pavel1387 commented on src/backend/LosTomates.PetHolidays.Application/Bookings/BookingsService.cs
> +    }
Может не фильтровать тут по статусу, а сделать например метод GetAll(Expression<Func<TEntity, bool>>? where = null) как в CrudService.
И в ендпоинт добавить параметр FromQuery чтобы на фронте был фильтр по статусам

2024-12-27 13:34 UTC, IlyaKo commented
@Desann69 Github пишет предупреждение, что какие-то скрытые символы в названии ветки, надо бы переименовать

2024-12-28 18:41 UTC, IlyaKo requested changes

2024-12-28 18:41 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.WebApi/Endpoints/BookingsEndPoints.cs
> +public class BookingsEndPoints
Остальные классы названы в единственном числе + Endpoints, этот предлагаю также назвать:  `BookingEndpoints`. Файл тоже надо будет переименовать

2024-12-28 18:41 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.WebApi/Endpoints/BookingsEndPoints.cs
> +        mapGroup.MapGet(string.Empty, async (IBookingsService service) => await service.GetAll())
Не очень понятно зачем такой метод может понадобится. 
По идее отель может получить все свои бронирования и владелец животного.

2024-12-28 18:41 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.WebApi/Extensions/ServiceCollectionExtensions.cs
> +        services.AddScoped<IBookingsService, BookingsService>();
Здесь была пустая строка перед return, очень хорошо отделяла визуально методы

2024-12-28 18:41 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Bookings/BookingsService.cs
> +public sealed class BookingsService(ApplicationDbContext dbContext, IValidator<BookingDto> validateService) : IBookingsService
Здесь и в интерфейсе предлагаю тоже переименовать в единственное число - `BookingService`. Наименования файлов соотетственно тоже. Причем namespace я бы оставил во множественным числом `Bookings`

2024-12-28 18:41 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Core/Domain/Bookings/BookingStatus.cs
А здесь точно нужны такие summary?

2025-01-21 14:06 UTC, Desann69 commented on src/backend/LosTomates.PetHolidays.Application/Bookings/BookingView.cs
> +}
классы PetView и RoomView уже существуют в Application

2025-01-21 14:13 UTC, Desann69 commented on src/backend/LosTomates.PetHolidays.WebApi/Endpoints/BookingsEndPoints.cs
> +        mapGroup.MapGet(string.Empty, async (IBookingsService service) => await service.GetAll())
Для админки я бы оставил

2025-01-21 14:19 UTC, Desann69 commented on src/backend/LosTomates.PetHolidays.Application/Bookings/IBookingsService.cs
> +}
Там же под капотом все равно идет поиск по entityId?

    private async Task<Booking?> FindEntityById(int entityId)
    {
        return await _dbContext.Bookings.FirstOrDefaultAsync(x => x.Id == entityId);
    }

2025-01-21 18:44 UTC, pavel1387 commented on src/backend/LosTomates.PetHolidays.Application/Bookings/IBookingsService.cs
> +}
@Desann69  я имею ввиду нужно добавить метод для получения всех бронирований юзера:
public interface IBookingsService
```
{
     Task<IReadOnlyList<BookingView>> GetByUserId(string userId);
    ...
}
```

а метод GetAll убрать, он действительно не нужен

2025-01-21 18:54 UTC, pavel1387 commented on src/backend/LosTomates.PetHolidays.Application/Bookings/BookingView.cs
> +}
> классы PetView и RoomView уже существуют в Application

@Desann69 я про добавить в этот класс поля PetView и RoomView, чтобы при получении бронирования получать данные о животном и комнате

public class BookingView
{
    ...
    public PetView Pet { get; set; }
  
    public RoomView Room { get; set; }
}

2025-01-21 18:59 UTC, pavel1387 reviewed
добавил комментарии

2025-01-22 19:34 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.WebApi/Endpoints/BookingsEndPoints.cs
> +        mapGroup.MapGet(string.Empty, async (IBookingsService service) => await service.GetAll())
Ок, пусть будет.

2025-01-22 19:34 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Bookings/BookingsService.cs
> +public sealed class BookingsService(ApplicationDbContext dbContext, IValidator<BookingDto> validateService) : IBookingsService
Интерфейс так и остался непереименован

2025-01-22 19:43 UTC, IlyaKo requested changes
Не по всем комментариям внесены изменения еще

2025-01-22 19:43 UTC, IlyaKo commented on src/backend/LosTomates.PetHolidays.Application/Bookings/IBookingsService.cs
Не хватает метода, который мы будем вызывать для изменения статуса бронирования. На твоё усмотрение как это сделать - один общий метод, куда передавать новый статус или отдельные методы для установки каждого статуса - заселение, отмена брони, выселение (окончание проживания)

2025-01-26 21:26 UTC, pavel1387 commented on src/backend/LosTomates.PetHolidays.Application/Bookings/BookingStatus.cs
> +    None,
Предлагаю убрать статус None и при создании Booking сразу ставить Created. Статус Removed мне кажется не нужен, т.к. есть Cancelled и для учебного проекта этого достаточно.
Можно еще добавить статус Completed

public enum BookingStatus : int
{
    Created = 0,
    Cancelled = 1,
    CheckIn = 2,
    Completed = 3
}

2025-01-26 21:30 UTC, pavel1387 commented
Как вариант еще добавить статус Confirmed, и когда создаем бронирование, владельцу отеля приходит уведомление и он  должен подтвердить его,  для этого можно использовать SignalR

2025-01-27 17:48 UTC, Koltrop approved these changes

2025-01-27 18:00 UTC, pavel1387 approved these changes

2025-01-27 22:40 UTC, IlyaKo approved these changes

2025-01-27 22:41 UTC, merged